config/routes.rb
#              login_daycare_workers GET|POST /daycare_workers/login(.:format)              daycare_workers#login
#     search_daycare_daycare_workers GET      /daycare_workers/search_daycare(.:format)     daycare_workers#search_daycare
#  select_department_daycare_workers GET|POST /daycare_workers/select_department(.:format)  daycare_workers#select_department
#             signup_daycare_workers POST     /daycare_workers/signup(.:format)             daycare_workers#signup
#      finish_signup_daycare_workers POST     /daycare_workers/finish_signup(.:format)      daycare_workers#finish_signup
#    congratulations_daycare_workers GET      /daycare_workers/congratulations(.:format)    daycare_workers#congratulations
#           dashboard_daycare_worker GET      /daycare_workers/:id/dashboard(.:format)      daycare_workers#dashboard
#                    daycare_workers GET      /daycare_workers(.:format)                    daycare_workers#index
#                                    POST     /daycare_workers(.:format)                    daycare_workers#create
#                 new_daycare_worker GET      /daycare_workers/new(.:format)                daycare_workers#new
#                edit_daycare_worker GET      /daycare_workers/:id/edit(.:format)           daycare_workers#edit
#                     daycare_worker GET      /daycare_workers/:id(.:format)                daycare_workers#show
#                                    PATCH    /daycare_workers/:id(.:format)                daycare_workers#update
#                                    PUT      /daycare_workers/:id(.:format)                daycare_workers#update
#                                    DELETE   /daycare_workers/:id(.:format)                daycare_workers#destroy
#              login_daycare_parents GET|POST /daycare_parents/login(.:format)              daycare_parents#login
#           dashboard_daycare_parent GET      /daycare_parents/:id/dashboard(.:format)      daycare_parents#dashboard
#                    daycare_parents GET      /daycare_parents(.:format)                    daycare_parents#index
#                                    POST     /daycare_parents(.:format)                    daycare_parents#create
#                 new_daycare_parent GET      /daycare_parents/new(.:format)                daycare_parents#new
#                edit_daycare_parent GET      /daycare_parents/:id/edit(.:format)           daycare_parents#edit
#                     daycare_parent GET      /daycare_parents/:id(.:format)                daycare_parents#show
#                                    PATCH    /daycare_parents/:id(.:format)                daycare_parents#update
#                                    PUT      /daycare_parents/:id(.:format)                daycare_parents#update
#                                    DELETE   /daycare_parents/:id(.:format)                daycare_parents#destroy
#      set_manager_password_password GET      /passwords/:id/set_manager_password(.:format) passwords#set_manager_password
#       set_worker_password_password GET      /passwords/:id/set_worker_password(.:format)  passwords#set_worker_password
#       set_parent_password_password GET      /passwords/:id/set_parent_password(.:format)  passwords#set_parent_password
#              set_password_password POST     /passwords/:id/set_password(.:format)         passwords#set_password
#                    share_todo_todo GET      /todos/:id/share_todo(.:format)               todos#share_todo
#        share_with_departments_todo GET|POST /todos/:id/share_with_departments(.:format)   todos#share_with_departments
#            share_with_workers_todo GET|POST /todos/:id/share_with_workers(.:format)       todos#share_with_workers
#            share_with_parents_todo GET|POST /todos/:id/share_with_parents(.:format)       todos#share_with_parents
#                   accept_todo_todo POST     /todos/:id/accept_todo(.:format)              todos#accept_todo
#                       search_todos GET      /todos/search(.:format)                       todos#search
#                              todos GET      /todos(.:format)                              todos#index
#                                    POST     /todos(.:format)                              todos#create
#                           new_todo GET      /todos/new(.:format)                          todos#new
#                          edit_todo GET      /todos/:id/edit(.:format)                     todos#edit
#                               todo GET      /todos/:id(.:format)                          todos#show
#                                    PATCH    /todos/:id(.:format)                          todos#update
#                                    PUT      /todos/:id(.:format)                          todos#update
#                                    DELETE   /todos/:id(.:format)                          todos#destroy
#                    confirm_account GET      /confirm_account(.:format)                    common#confirm_account
#                        admin_login GET|POST /admin/login(.:format)                        admin/admin#login
#                    admin_dashboard GET      /admin/dashboard(.:format)                    admin/admin#dashboard
#             admin_select_privilege GET      /admin/select_privilege(.:format)             admin/admin#select_privilege
#                admin_set_privilege GET|POST /admin/set_privilege(.:format)                admin/admin#set_privilege
#                admin_functionality GET      /admin/functionality(.:format)                admin/admin#functionality
#         admin_fetch_customer_types GET      /admin/fetch_customer_types(.:format)         admin/admin#fetch_customer_types
#              admin_fetch_customers GET      /admin/fetch_customers(.:format)              admin/admin#fetch_customers
#         import_new_admin_customers GET      /admin/customers/import_new(.:format)         admin/customers#import_new
#             import_admin_customers POST     /admin/customers/import(.:format)             admin/customers#import
# add_customer_types_admin_customers GET|POST /admin/customers/add_customer_types(.:format) admin/customers#add_customer_types
#        notify_users_admin_customer GET|POST /admin/customers/:id/notify_users(.:format)   admin/customers#notify_users
#                  todos_admin_todos GET      /admin/todos/todos(.:format)                  admin/todos#todos
#          todo_assignee_admin_todos GET      /admin/todos/todo_assignee(.:format)          admin/todos#todo_assignee
#                 search_admin_todos GET      /admin/todos/search(.:format)                 admin/todos#search
#                        admin_todos GET      /admin/todos(.:format)                        admin/todos#index
#                                    POST     /admin/todos(.:format)                        admin/todos#create
#                     new_admin_todo GET      /admin/todos/new(.:format)                    admin/todos#new
#                    edit_admin_todo GET      /admin/todos/:id/edit(.:format)               admin/todos#edit
#                         admin_todo GET      /admin/todos/:id(.:format)                    admin/todos#show
#                                    PATCH    /admin/todos/:id(.:format)                    admin/todos#update
#                                    PUT      /admin/todos/:id(.:format)                    admin/todos#update
#                                    DELETE   /admin/todos/:id(.:format)                    admin/todos#destroy
#                      api_api_helps GET      /api/help(.:format)                           api/api_helps#index
#                       api_v1_login POST     /api/v1/login(.:format)                       api/v1/sessions#create
#                      api_v1_signup POST     /api/v1/signup(.:format)                      api/v1/registrations#create
#            api_v1_daycare_managers GET      /api/v1/daycare_managers(.:format)            api/v1/daycare_managers#index
#                                    POST     /api/v1/daycare_managers(.:format)            api/v1/daycare_managers#create
#         new_api_v1_daycare_manager GET      /api/v1/daycare_managers/new(.:format)        api/v1/daycare_managers#new
#        edit_api_v1_daycare_manager GET      /api/v1/daycare_managers/:id/edit(.:format)   api/v1/daycare_managers#edit
#             api_v1_daycare_manager GET      /api/v1/daycare_managers/:id(.:format)        api/v1/daycare_managers#show
#                                    PATCH    /api/v1/daycare_managers/:id(.:format)        api/v1/daycare_managers#update
#                                    PUT      /api/v1/daycare_managers/:id(.:format)        api/v1/daycare_managers#update
#                                    DELETE   /api/v1/daycare_managers/:id(.:format)        api/v1/daycare_managers#destroy
#             api_v1_daycare_workers GET      /api/v1/daycare_workers(.:format)             api/v1/daycare_workers#index
#                                    POST     /api/v1/daycare_workers(.:format)             api/v1/daycare_workers#create
#          new_api_v1_daycare_worker GET      /api/v1/daycare_workers/new(.:format)         api/v1/daycare_workers#new
#         edit_api_v1_daycare_worker GET      /api/v1/daycare_workers/:id/edit(.:format)    api/v1/daycare_workers#edit
#              api_v1_daycare_worker GET      /api/v1/daycare_workers/:id(.:format)         api/v1/daycare_workers#show
#                                    PATCH    /api/v1/daycare_workers/:id(.:format)         api/v1/daycare_workers#update
#                                    PUT      /api/v1/daycare_workers/:id(.:format)         api/v1/daycare_workers#update
#                                    DELETE   /api/v1/daycare_workers/:id(.:format)         api/v1/daycare_workers#destroy
#             api_v1_daycare_parents GET      /api/v1/daycare_parents(.:format)             api/v1/daycare_parents#index

app/models/daycare.rb
# == Schema Information
#
# Table name: daycares
#
#  id               :integer          not null, primary key
#  name             :string
#  address_line1    :string
#  post_code        :string
#  country          :string
#  telephone        :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  customer_type_id :integer
#  language         :string
#

require 'csv'
class Daycare < ActiveRecord::Base
  has_one  :manager, dependent: :destroy
  has_many :workers, dependent: :destroy
  has_many :parents, dependent: :destroy
  # has_many :children, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_many :departments, dependent: :destroy
  has_many :todos, dependent: :destroy
  has_many :create_permissions, dependent: :destroy
  has_many :edit_permissions, dependent: :destroy
  has_many :view_permissions, dependent: :destroy
  has_many :report_permissions, dependent: :destroy
  # has_many :daycare_todos, dependent: :destroy
  # has_many :todos, through: :daycare_todos
  belongs_to :customer_type

  validates :name, :country, :language, :address_line1, :customer_type_id, presence: true

  accepts_nested_attributes_for :manager, :departments, allow_destroy: true, reject_if: :all_blank
  
  def self.import(file, customer_type_id)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      unless Manager.exists?(email: row['Daycare Manager Email'])
        @daycare = Daycare.new
        @daycare.country = row['Country']
        @daycare.language = row['Language']
        @daycare.name = row['Customer Name']
        @daycare.address_line1 = row['Address']
        @daycare.post_code = row['Postcode'].to_s
        @daycare.telephone = row['Telephone'].to_s
        @daycare.customer_type_id = customer_type_id

        CSV.parse_line(row['Department Names']).each do |name|
          @daycare.departments.build(department_name: name)
        end
        manager = @daycare.build_manager
        manager.name = row['Daycare Manager Name']
        manager.email = row['Daycare Manager Email']
        manager.password = Devise.friendly_token.first(8)

        CSV.parse_line(row['Daycare Worker Names']).each_with_index do |name, index|
          @worker = @daycare.workers.build(name: name)
          email = CSV.parse_line(row['Daycare Worker Emails'])[index]
          @worker.email = email if email.present?
          @worker.password = Devise.friendly_token.first(8)
        end

        # CSV.parse_line(row['Daycare Children Names']).each do |name|
        #   @child = @daycare.children.build(name: name)
        # end

        CSV.parse_line(row['Daycare Parent Names']).each_with_index do |name, index|
          @worker = @daycare.parents.build(name: name)
          email = CSV.parse_line(row['Daycare Parent Emails'])[index]
          @worker.email = email if email.present?
          @worker.password = Devise.friendly_token.first(8)
        end
      end
    end
    @daycare
  end
  
  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, packed: nil, file_warning: :ignore)
    when ".xls" then Roo::Excel.new(file.path, packed: nil, file_warning: :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/models/parent.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  role_id                :integer
#  daycare_id             :integer
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  type                   :string
#  name                   :string
#  set_password_token     :string
#  api_key                :string
#  department_id          :integer
#  username               :string
#
# Indexes
#
#  index_users_on_department_id         (department_id)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class Parent < User
  has_many :children, dependent: :destroy
  has_many :departments, through: :children

  accepts_nested_attributes_for :children, allow_destroy: true

  validates :daycare_id, presence: true
  
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<%= f.fields_for :icon do |image| %>
  <div class="c_list_1 c_list_3">
    <h4>Add Icon</h4>
  </div>
  <div class="c_list_1_in c_list_1_in2">
    <%= image.file_field :image, class: "c_list_1" %>
  </div>
<% end %>


<div class="schedule_col">
  <div class="schedule_field">
    <div class="sehedule_dt_tm">
      <label>Todo Frequency</label>
      <%= f.select(:frequency, Todo::FREQUENCY, {}, {:class => 'select_frequency'})%>
    </div>
    <div class="sehedule_dt_tm" id="repeat_opt" style="display:none;">
      <label>Repeat At</label>
      <%= f.select(:recurring_rule, Todo::RECURRANCE_OPTIONS, {prompt: "Select Repeat Options"}, {:class => ''})%>
    </div>
  </div>


<div class="schedule_col">
  <div class="schedule_field">
    <div class="sehedule_dt_tm">
      <label>Schedule Date / time</label>
      <%if @todo.new_record?%>
        <%=f.text_field :schedule_date, placeholder: 'Choose Schedule date and time', class: 'datetimepicker', readonly: true%>
      <%else%>
        <%=f.text_field :schedule_date, placeholder: 'Choose Schedule date and time', class: 'datetimepicker', readonly: true, disabled: true%>
        <%=f.hidden_field :schedule_date, value: @todo.schedule_date %>
      <%end%>
    </div>
    <a class="sc_cal_icon fl"></a>
    <div class="sehedule_dt_tm">
      <label>Due Date / time</label>
      <%if @todo.new_record?%>
        <%=f.text_field :due_date, placeholder: 'Choose Completion date and time', class: 'datetimepicker', readonly: true%>
      <%else%>
        <%=f.text_field :due_date, placeholder: 'Choose Completion date and time', class: 'datetimepicker', readonly: true, disabled: true%>
        <%=f.hidden_field :due_date, value: @todo.due_date %>
      <%end%>
    </div>
  </div>

  <div class="schedule_field">
    <%#= select_tag :customer_type_id, options_from_collection_for_select(CustomerType.all, 'id', 'name'), prompt: 'Select Frequency', class: 'todo_select', required: true %>
  </div>

  <div class="schedule_field">
    <div class="sc_1">
      <label>Is Delegatable</label>
      <div class="">
        <%=f.check_box :is_delegatable%>
      </div>
    </div>
  </div>

  <div class="schedule_field">
    <div class="sc_1">
      <label>Is Circulatable</label>
      <div class="">
        <%=f.check_box :is_circulatable%>
      </div>    
    </div>
  </div>

  <div class="schedule_field">
    <div class="sc_1">
      <label>Add Title</label>
      <div class="add_key_task">
        <%if @todo.new_record?%>
          <%=f.text_field :title, class: 'key_task_input', placeholder: 'Title'%>
        <%else%>
          <%=f.text_field :title, class: 'key_task_input', placeholder: 'Title', disabled: true%>
        <%end%>
      </div>
      <%= f.link_to_add "Add Key <br/>Task".html_safe, :key_tasks, class: 'add_file' %>
    </div>
  </div>
  <div class="schedule_field">
    <div class="sc_1">
      <%=f.fields_for :key_tasks do |key_task|%>
        <label class="pdleft_40">Key Task</label>
        <span class="sc_no">1</span>
        <div class="add_key_task wdt77">
          <%=key_task.text_field :name, class: 'key_task_input', placeholder: 'Task Name'%>
          <%= key_task.link_to_remove "", class: 'close_img' %>
        </div>
        <%= key_task.link_to_add "Add Sub <br/>Task".html_safe, :sub_tasks, class: 'add_file sub_task_btn' %>
        <div class="add_sub_task_col">
          <div class="sc_1">
            <label>Sub Task</label>
            <%=key_task.fields_for :sub_tasks do |sub_task|%>
              <div class="add_key_task">
                <%=sub_task.text_field :name, class: 'key_task_input', placeholder: 'Sub Task Name'%> 
                <%= sub_task.link_to_remove "", class: 'close_img' %>
              </div>
              <!-- <div class="add_key_task">
                <input name="" type="text" class="key_task_input" placeholder="Save tress"> 
                <a class="close_img" href="#"></a>
              </div> -->
            <%end%>
          </div>
        </div>
      <%end%>
    </div>
  </div>
  <%=f.submit 'Save', class: 'submit_btn mar_b'%>
</div>

<script type="text/javascript">
  $(".select_frequency").change(function(){
    if($(".select_frequency").val() == "" || $(".select_frequency").val() == "One Time Event"){
      $("#todo_recurring_rule").val("")
      $("#repeat_opt").hide()
      
    }else
    {      
      $("#todo_recurring_rule").val("")
      $("#repeat_opt").show()
    }
  });

  $( document ).ready(function() {
    if($(".select_frequency").val() == "" || $(".select_frequency").val() == "One Time Event"){
      $("#todo_recurring_rule").val("")
      $("#repeat_opt").hide()      
    }else
    {      
      $("#repeat_opt").show()
    }
  });
</script>

app/views/todos/_form_new.html.erb
<div class="mid_wrapp padd34">
  <div class="c_list_1 c_list_3">
    <h4>Add Icon</h4>
  </div>
  <div class="c_list_1">
    <h4>Environment Day</h4>
    <div class="c_list_1_in c_list_1_in2">
      <img src="images/e_img5.jpg" width="159" height="158"> 
    </div>
  </div>
  <div class="schedule_col">
    <div class="schedule_field">
      <div class="sehedule_dt_tm">
        <label>Schedule Date / time</label>
        <input name="" type="text" placeholder="10-07-2015/ 10:30">
      </div>
      <a class="sc_cal_icon fl"></a>
      <div class="sehedule_dt_tm">
        <label>Due Date / time</label>
        <input name="" type="text" placeholder="20-07-2015/ 10:30">
      </div>
    </div>
    <div class="schedule_field">
      <div class="sc_1">
        <label>Add Title</label>
        <div class="add_key_task">
          <input name="" type="text" class="key_task_input" placeholder="Environment Day"> 
        </div>
        <a class="add_file" href="javascript:;" id="add_key_task">Add Key <br/>Task</a>
      </div>
    </div>
    <div id="key_task_fields">
      <div class="schedule_field">
        <div class="sc_1">
          <label class="pdleft_40">Key Task</label>
          <span class="sc_no">1</span>
          <div class="add_key_task wdt77">
            <input name="" type="text" class="key_task_input" placeholder="Planting Tress"> 
            <a class="close_img" href="#"></a>
          </div>
          <a class="add_file sub_task_btn add_sub_task" href="javascript:;">Add Sub <br/>Task</a>
          <div class="add_sub_task_col">
            <div class="sc_1 sub_task_div">
              <label>Sub Task</label>
              <div class="add_key_task subtask_div">
                <input name="" type="text" class="key_task_input" placeholder="Spech for not to cut trees"> 
                <a class="close_img close_subtask" href="javascript:;"></a>
              </div>
              <!-- <div class="add_key_task">
                <input name="" type="text" class="key_task_input" placeholder="Save tress"> 
                <a class="close_img" href="#"></a>
              </div> -->
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- <div class="schedule_field">
      <div class="sc_1">
        <label class="pdleft_40">Key Task</label>
        <span class="sc_no">2</span>
        <div class="add_key_task wdt77">
          <input name="" type="text" class="key_task_input" placeholder="Planting Tress"> 
          <a class="close_img" href="#"></a>
        </div>
        <a class="add_file sub_task_btn" href="#">Add Sub <br/>Task</a>
        <div class="add_sub_task_col">
          <div class="sc_1">
            <label>Sub Task</label>
            <div class="add_key_task">
              <input name="" type="text" class="key_task_input" placeholder="Spech for not to cut trees"> 
              <a class="close_img" href="#"></a>
            </div>
            <div class="add_key_task">
              <input name="" type="text" class="key_task_input" placeholder="Save tress"> 
              <a class="close_img" href="#"></a>
            </div>
          </div>
        </div>
      </div>
    </div> -->
    <input name="" type="button" class="submit_btn mar_b" onClick="location.href='share_to_do.html'" value="Create">
  </div>
</div>
<script type="text/javascript">
  $("#add_key_task").click(function(){
    $("#key_task_fields").append('<div class="schedule_field"><div class="sc_1"><label class="pdleft_40">Key Task</label><span class="sc_no">1</span><div class="add_key_task wdt77"><input name="" type="text" class="key_task_input" placeholder="Planting Tress"><a class="close_img" href="#"></a></div><a class="add_file sub_task_btn" href="#">Add Sub <br>Task</a><div class="add_sub_task_col"><div class="sc_1"><label>Sub Task</label><div class="add_key_task"><input name="" type="text" class="key_task_input" placeholder="Spech for not to cut trees"><a class="close_img" href="#"></a></div><div class="add_key_task"><input name="" type="text" class="key_task_input" placeholder="Save tress"><a class="close_img" href="#"></a></div></div></div></div></div>');
  });
  $(".add_sub_task").click(function(){
    $(this).next().find('.sub_task_div').append('<div class="add_key_task subtask_div"><input name="" type="text" class="key_task_input" placeholder="Plant Trees"><a class="close_img close_subtask" href="javascript:;"></a></div>');
  });
  $('.close_subtask').click(function(){
    alert('hi')
    // $(this).closest('.subtask_div').remove();
  });
</script>

app/views/todos/index.html.erb
<%=render 'todo_actions'%>

app/views/todos/share_with_departments.html.erb
<div class="hgt_auto">
  <div class="header_top_row">
    <span class="back_btn"><a href="/">&nbsp;</a></span>
    <span class="menu_icons">
      <div class="submenu_toggle">
        <ul>
          <li><a href="/">Home</a></li>
          <%if current_user%>
            <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
          <%end%>
        </ul>
      </div>
    </span>
  </div>
</div>
<div class="mid_wrapp padd34">
  <%=form_tag share_with_departments_todo_path(@todo), method: :post do%>
    <div class="sel_col">
      <a class="select_txt" href="#">Select All</a>
    </div>
    <div class="custom_checbox_list">
      <ul>
        <%current_daycare.departments.each do |department|%>
          <li>
            <%= check_box_tag 'department_ids[]', department.id, false, :id => "department_id_#{department.id}" %>
            <label for="department_id_<%=department.id%>"><%=department.department_name%></label>
          </li>
        <%end%>
      </ul>
    </div>
    <!-- <div class="task_com_col">
      <h4>Once task are completed todo list delegatable</h4>
      <span class="yes_no">
      <a href="#" class="yn_active">Yes</a>
      <a href="#">No</a>
      </span>
    </div> -->
    <input name="" type="submit" class="submit_btn" value="Submit">
  <%end%>
</div>

app/views/todos/share_with_parents.html.erb
<div class="hgt_auto">
  <div class="header_top_row">
    <span class="back_btn"><a href="/">&nbsp;</a></span>
    <span class="menu_icons">
      <div class="submenu_toggle">
        <ul>
          <li><a href="/">Home</a></li>
          <%if current_user%>
            <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
          <%end%>
        </ul>
      </div>
    </span>
  </div>
</div>
<div class="mid_wrapp padd34">
  <%=form_tag share_with_parents_todo_path(@todo), method: :post do%>
    <div class="sel_col">
      <a class="select_txt" href="#">Select All</a>
    </div>
    <div class="custom_checbox_list">
      <ul>
        <%current_daycare.parents.each do |parent|%>
          <li>
            <%= check_box_tag 'parent_ids[]', parent.id, false, :id => "parent_id_#{parent.id}" %>
            <label for="parent_id_<%=parent.id%>"><%=parent.name%></label>
          </li>
        <%end%>
      </ul>
    </div>
  <!--   <div class="task_com_col">
      <h4>Once task are completed todo list delegatable</h4>
      <span class="yes_no">
      <a href="#" class="yn_active">Yes</a>
      <a href="#">No</a>
      </span>
    </div> -->
    <input name="" type="submit" class="submit_btn" value="Submit">
  <%end%>
</div>

app/views/todos/share_with_workers.html.erb
<div class="hgt_auto">
  <div class="header_top_row">
    <span class="back_btn"><a href="/">&nbsp;</a></span>
    <span class="menu_icons">
      <div class="submenu_toggle">
        <ul>
          <li><a href="/">Home</a></li>
          <%if current_user%>
            <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
          <%end%>
        </ul>
      </div>
    </span>
  </div>
</div>
<div class="mid_wrapp padd34">
  <%=form_tag share_with_workers_todo_path(@todo), method: :post do%>
    <div class="sel_col">
      <a class="select_txt" href="#">Select All</a>
    </div>
    <div class="custom_checbox_list">
      <ul>
        <%current_daycare.workers.each do |worker|%>
          <li>
            <%= check_box_tag 'worker_ids[]', worker.id, false, :id => "worker_id_#{worker.id}" %>
            <label for="worker_id_<%=worker.id%>"><%=worker.name%></label>
          </li>
        <%end%>
      </ul>
    </div>
<!--     <div class="task_com_col">
      <h4>Once task are completed todo list delegatable</h4>
      <span class="yes_no">
      <a href="#" class="yn_active">Yes</a>
      <a href="#">No</a>
      </span>
    </div> -->
    <input name="" type="submit" class="submit_btn" value="Submit">
  <%end%>
</div>

app/views/todos/todo_departments.html.erb
<div class="hgt_auto">
  <div class="header_top_row">
    <span class="back_btn"><a href="/">&nbsp;</a></span>
    <span class="menu_icons">
      <div class="submenu_toggle">
        <ul>
          <li><a href="/">Home</a></li>
          <%if current_user%>
            <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
          <%end%>
        </ul>
      </div>
    </span>
  </div>
</div>
<div class="mid_wrapp padd34">
  <%=form_tag todo_departments_todo_path(@todo), method: :post do%>
    <div class="sel_col">
      <a class="select_txt" href="#">Select All</a>
    </div>
    <div class="custom_checbox_list">
      <ul>
        <%current_daycare.departments.each do |department|%>
          <li>
            <%= check_box_tag 'department_ids[]', department.id, false, :id => "department_id_#{department.id}" %>
            <label for="department_id_<%=department.id%>"><%=department.department_name%></label>
          </li>
        <%end%>
      </ul>
    </div>
    <div class="task_com_col">
      <h4>Once task are completed todo list delegatable</h4>
      <span class="yes_no">
      <a href="#" class="yn_active">Yes</a>
      <a href="#">No</a>
      </span>
    </div>
    <input name="" type="submit" class="submit_btn" value="Submit">
  <%end%>
</div>