config/routes.rb
# == Route Map
#
#                             Prefix Verb     URI Pattern                                   Controller#Action
#                   new_user_session GET      /users/sign_in(.:format)                      devise/sessions#new
#                       user_session POST     /users/sign_in(.:format)                      devise/sessions#create
#               destroy_user_session DELETE   /users/sign_out(.:format)                     devise/sessions#destroy
#                      user_password POST     /users/password(.:format)                     devise/passwords#create
#                  new_user_password GET      /users/password/new(.:format)                 devise/passwords#new
#                 edit_user_password GET      /users/password/edit(.:format)                devise/passwords#edit
#                                    PATCH    /users/password(.:format)                     devise/passwords#update
#                                    PUT      /users/password(.:format)                     devise/passwords#update
#           cancel_user_registration GET      /users/cancel(.:format)                       devise/registrations#cancel
#                  user_registration POST     /users(.:format)                              devise/registrations#create
#              new_user_registration GET      /users/sign_up(.:format)                      devise/registrations#new
#             edit_user_registration GET      /users/edit(.:format)                         devise/registrations#edit
#                                    PATCH    /users(.:format)                              devise/registrations#update
#                                    PUT      /users(.:format)                              devise/registrations#update
#                                    DELETE   /users(.:format)                              devise/registrations#destroy
#                               root GET      /                                             welcome#index
#                     login_daycares GET|POST /daycares/login(.:format)                     daycares#login
#            add_departments_daycare GET|POST /daycares/:id/add_departments(.:format)       daycares#add_departments
#            congratulations_daycare GET      /daycares/:id/congratulations(.:format)       daycares#congratulations
#             invite_parents_daycare GET|POST /daycares/:id/invite_parents(.:format)        daycares#invite_parents
#             invite_workers_daycare GET|POST /daycares/:id/invite_workers(.:format)        daycares#invite_workers
#                           daycares GET      /daycares(.:format)                           daycares#index
#                                    POST     /daycares(.:format)                           daycares#create
#                        new_daycare GET      /daycares/new(.:format)                       daycares#new
#                       edit_daycare GET      /daycares/:id/edit(.:format)                  daycares#edit
#                            daycare GET      /daycares/:id(.:format)                       daycares#show
#                                    PATCH    /daycares/:id(.:format)                       daycares#update
#                                    PUT      /daycares/:id(.:format)                       daycares#update
#                                    DELETE   /daycares/:id(.:format)                       daycares#destroy
#              login_daycare_workers GET|POST /daycare_workers/login(.:format)              daycare_workers#login
#     search_daycare_daycare_workers GET      /daycare_workers/search_daycare(.:format)     daycare_workers#search_daycare
#  select_department_daycare_workers GET|POST /daycare_workers/select_department(.:format)  daycare_workers#select_department
#             signup_daycare_workers POST     /daycare_workers/signup(.:format)             daycare_workers#signup
#      finish_signup_daycare_workers POST     /daycare_workers/finish_signup(.:format)      daycare_workers#finish_signup
#    congratulations_daycare_workers GET      /daycare_workers/congratulations(.:format)    daycare_workers#congratulations
#           dashboard_daycare_worker GET      /daycare_workers/:id/dashboard(.:format)      daycare_workers#dashboard
#                    daycare_workers GET      /daycare_workers(.:format)                    daycare_workers#index
#                                    POST     /daycare_workers(.:format)                    daycare_workers#create
#                 new_daycare_worker GET      /daycare_workers/new(.:format)                daycare_workers#new
#                edit_daycare_worker GET      /daycare_workers/:id/edit(.:format)           daycare_workers#edit
#                     daycare_worker GET      /daycare_workers/:id(.:format)                daycare_workers#show
#                                    PATCH    /daycare_workers/:id(.:format)                daycare_workers#update
#                                    PUT      /daycare_workers/:id(.:format)                daycare_workers#update
#                                    DELETE   /daycare_workers/:id(.:format)                daycare_workers#destroy
#              login_daycare_parents GET|POST /daycare_parents/login(.:format)              daycare_parents#login
#           dashboard_daycare_parent GET      /daycare_parents/:id/dashboard(.:format)      daycare_parents#dashboard
#                    daycare_parents GET      /daycare_parents(.:format)                    daycare_parents#index
#                                    POST     /daycare_parents(.:format)                    daycare_parents#create
#                 new_daycare_parent GET      /daycare_parents/new(.:format)                daycare_parents#new
#                edit_daycare_parent GET      /daycare_parents/:id/edit(.:format)           daycare_parents#edit
#                     daycare_parent GET      /daycare_parents/:id(.:format)                daycare_parents#show
#                                    PATCH    /daycare_parents/:id(.:format)                daycare_parents#update
#                                    PUT      /daycare_parents/:id(.:format)                daycare_parents#update
#                                    DELETE   /daycare_parents/:id(.:format)                daycare_parents#destroy
#      set_manager_password_password GET      /passwords/:id/set_manager_password(.:format) passwords#set_manager_password
#       set_worker_password_password GET      /passwords/:id/set_worker_password(.:format)  passwords#set_worker_password
#       set_parent_password_password GET      /passwords/:id/set_parent_password(.:format)  passwords#set_parent_password
#              set_password_password POST     /passwords/:id/set_password(.:format)         passwords#set_password
#                    share_todo_todo GET      /todos/:id/share_todo(.:format)               todos#share_todo
#        share_with_departments_todo GET|POST /todos/:id/share_with_departments(.:format)   todos#share_with_departments
#            share_with_workers_todo GET|POST /todos/:id/share_with_workers(.:format)       todos#share_with_workers
#            share_with_parents_todo GET|POST /todos/:id/share_with_parents(.:format)       todos#share_with_parents
#                   accept_todo_todo POST     /todos/:id/accept_todo(.:format)              todos#accept_todo
#                       search_todos GET      /todos/search(.:format)                       todos#search
#                              todos GET      /todos(.:format)                              todos#index
#                                    POST     /todos(.:format)                              todos#create
#                           new_todo GET      /todos/new(.:format)                          todos#new
#                          edit_todo GET      /todos/:id/edit(.:format)                     todos#edit
#                               todo GET      /todos/:id(.:format)                          todos#show
#                                    PATCH    /todos/:id(.:format)                          todos#update
#                                    PUT      /todos/:id(.:format)                          todos#update
#                                    DELETE   /todos/:id(.:format)                          todos#destroy
#                    confirm_account GET      /confirm_account(.:format)                    common#confirm_account
#                        admin_login GET|POST /admin/login(.:format)                        admin/admin#login
#                    admin_dashboard GET      /admin/dashboard(.:format)                    admin/admin#dashboard
#             admin_select_privilege GET      /admin/select_privilege(.:format)             admin/admin#select_privilege
#                admin_set_privilege GET|POST /admin/set_privilege(.:format)                admin/admin#set_privilege
#                admin_functionality GET      /admin/functionality(.:format)                admin/admin#functionality
#         admin_fetch_customer_types GET      /admin/fetch_customer_types(.:format)         admin/admin#fetch_customer_types
#              admin_fetch_customers GET      /admin/fetch_customers(.:format)              admin/admin#fetch_customers
#         import_new_admin_customers GET      /admin/customers/import_new(.:format)         admin/customers#import_new
#             import_admin_customers POST     /admin/customers/import(.:format)             admin/customers#import
# add_customer_types_admin_customers GET|POST /admin/customers/add_customer_types(.:format) admin/customers#add_customer_types
#        notify_users_admin_customer GET|POST /admin/customers/:id/notify_users(.:format)   admin/customers#notify_users
#                  todos_admin_todos GET      /admin/todos/todos(.:format)                  admin/todos#todos
#          todo_assignee_admin_todos GET      /admin/todos/todo_assignee(.:format)          admin/todos#todo_assignee

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id           :integer          not null, primary key
#  device_token :string
#  device_type  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Device < ActiveRecord::Base

  VALID_DEVICES = %w(android ios)
  has_many :user_devices
  has_many :users, through: :user_devices

  # has_one :active_user_device, conditions: {status: :active}, class_name: 'UserDevice'
  # has_one :active_user, through: :active_user_device, source: :user
  validates :device_token, :device_type, presence: true
  validates :device_token, uniqueness: { scope: [:device_type]}
  validate :valid_device_type
  scope :with_type, lambda { |type| where("device_type = ?", type)}
  scope :with_token, lambda { |token| where("device_token = ?",token)}

  def self.with_token_and_type(device_token, device_type)
    with_type(device_type).with_token(device_token).first
  end

  private
    def valid_device_type
      errors.add(:device_type, "is invalid") unless Device::VALID_DEVICES.include?(device_type)
    end 
end

app/views/admin/admin/_choose_customer.html.erb
<%multi_select ||= false%>
<%path ||= nil%>
<div class="priv_col_wrapper">
  <div class="sel_col mrg_bot_zero">
    <h4>Customer</h4>
    <%if multi_select == true%>
      <a class="select_txt cust_select_all" href="javascript:;">Select All</a>
      <%name = 'daycare_id[]'%>
    <%else%>
      <%name = 'daycare_id'%>
    <%end%>
  </div>
  <div class="custom_checbox_list admin_tic_chkbox">
    <ul>
      <%if customers.present?%>
        <%customers.each do |customer|%>
          <li>
            <input type="checkbox" name="<%=name%>" class="cust_check" id="customer_<%=customer.id%>" value="<%=customer.id%>" />
            <label for="customer_<%=customer.id%>"><%=customer.name%></label>
          </li>
        <%end%>
      <%else%>
        <li>There are no customer. Please select another customer type</li>
      <%end%>
    </ul>
  </div>
</div>

<%if path == "admin_todos"%>
  <div class="priv_col_wrapper">
    <div class="sel_col mrg_bot_zero">
      <h4>Whom the to do list is to be created for?</h4>
    </div>
    <div class="custom_checbox_list admin_tic_chkbox">
      <%=form_tag todo_assignee_admin_todos_path, method: :get, remote: true do%>
        <ul>
          <li>
            <input type="checkbox" name="todo_assignee" class="type_check" id="department_todo" value="departments" />
            <label for="department_todo">For Departments</label>
          </li>
          <li>
            <input type="checkbox" name="todo_assignee" class="type_check" id="users_todo" value="users"/>
            <label for="users_todo">For Users</label>
          </li>
        </ul>
      <%end%>
    </div>
  </div>
<%end%>

<%unless path == 'admin_todos'%>
  <%if customers.present? %>
    <%=form_tag admin_set_privilege_path, method: :get, id: 'functionality_form' do%>
      <%=hidden_field_tag :daycare_id %>
      <%=render 'choose_user_type', multi_select: multi_select, path: path%>
      <%=hidden_field_tag :functionality unless path == "admin_todos" %>
      <%=render 'choose_functionality' unless path == "admin_todos" %>
    <%end%>
  <%end%>
<%end%>


<%if multi_select == true%>
  <script type="text/javascript">
    $('.cust_select_all').click(function(){
      $('.cust_check').trigger('click');
      $('#all_customer').val('true')
    });
    $('.cust_check').click(function(){
      $('#customer_id').val($(this).val())
    })

    var selectedTypeBox = null;
    $(".type_check").click(function() {
      selectedTypeBox = this.id;

      $(".type_check").each(function() {
        if ( this.id == selectedTypeBox ){
          this.checked = true;
          $('#daycare_id').val($(this).val());
        }else{
          this.checked = false;
        };
      });
      $(this).closest('form').submit();
    });
  </script>
<%else%>
  <script type="text/javascript">
    var selectedBox = null;
    var arr = [];
    $(".cust_check").click(function() {
      selectedBox = this.id;

      $(".cust_check").each(function() {
        if ( this.id == selectedBox ){
          this.checked = true;
          $('#daycare_id').val($(this).val());
        }else{
          this.checked = false;
        };
      });
    });

    $('.functionality_link').click(function(){
      functionality = $(this).data('name');
      $('#functionality').val(functionality);
      $('#functionality_form').submit();
    });
  </script>
<%end%>

app/views/admin/admin/_choose_customer_type.html.erb
<%multi_select ||= false%>
<div class="priv_col_wrapper">
  <div class="sel_col mrg_bot_zero">
    <h4>Customer Type</h4>
    <%if multi_select == true%>
      <a class="select_txt" href="javascript:;">Select All</a>
    <%end%>
  </div>
  <div class="custom_checbox_list admin_tic_chkbox">
    <ul>
      <%if customer_types.present? %>
        <%=form_tag admin_fetch_customers_path(path: @path), method: :get, remote: true do%>
          <%customer_types.all.each do |customer_type|%>
            <li>
              <input type="checkbox" name="customer_type_id[]" class="cust_type" id="customer_type_<%=customer_type.id%>" value="<%=customer_type.id%>" />
              <label for="customer_type_<%=customer_type.id%>"><%=customer_type.name%></label>
            </li>
          <%end%>
        <%end%>
      <%else%>
        <li>There are no customer types in this country</li>
      <%end%>
    </ul>
  </div>
</div>
<%if multi_select == true%>
<%else%>

<%end%>
<script type="text/javascript">
  
  $('.cust_type').click(function(){
    $(this).closest('form').submit();
  });

  $('.select_txt').click(function(){
    $('.cust_type').click();
    $('#all_customer_type').val('true');
  });

  $('.cust_type').click(function(){
    $('#customer_type_id').val($(this).val())
  });
  
</script>

app/views/admin/admin/_choose_functionality.html.erb
<div class="priv_col_wrapper">
  <div class="sel_col mrg_bot_zero">
    <h4>Functionality</h4>
  </div>
  <div class="d_input_wrap">
    <ul>
      <li><a href="javascript:;" class="functionality_link" data-name="Todo">Todo List</a></li>
      <li><a href="javascript:;" class="functionality_link" data-name="Allergy">Allergy</a></li>
      <li><a href="javascript:;" class="functionality_link" data-name="Medication">Medication</a></li>
      <li><a href="javascript:;" class="functionality_link" data-name="NoticeBoard">Notice Board</a></li>
      <li><a href="javascript:;" class="functionality_link" data-name="Attendence">Attendance</a></li>
      <li><a href="javascript:;" class="functionality_link" data-name="Calender">Calender</a></li>
      <li><a href="javascript:;" class="functionality_link" data-name="Intolerence">Intolerance</a></li>
    </ul>
  </div>
</div>

app/views/admin/admin/_choose_user_type.html.erb
<div class="priv_col_wrapper">
  <div class="sel_col mrg_bot_zero">
    <h4>User Type</h4>
    <a class="select_txt select_user_type" href="javascript:;">Select All</a>
  </div>
  <div class="custom_checbox_list admin_tic_chkbox">
    <ul>
      <li>
        <input type="checkbox" class="user_type_common" name="user_type[]" id="manager_type" value="Manager" />
        <label for="manager_type">Daycare Manager</label>
      </li>
      <li>
        <input type="checkbox" class="user_type_common" name="user_type[]" id="worker_type" value="Worker" />
        <label for="worker_type">Daycare Workers</label>
      </li>
      <li>
        <input type="checkbox" class="user_type_common" name="user_type[]" id="parents_type" value="Parent" />
        <label for="parents_type">Daycare Parents</label>
      </li>
      <li>
        <input type="checkbox" class="user_type_common" name="user_type[]" id="partner_type" value="Partner" />
        <label for="partner_type">Daycare Partner</label>
      </li>
    </ul>
  </div>
</div>
<script type="text/javascript">
  $('.select_user_type').click(function(){
    $('.user_type_common').click();
  });
  $('.user_type_common').click(function(){
    // $('#user_type_').val($(this).val());
    var arr = []
    $('.user_type_common').each(function(){
      if($(this).is(':checked')){
        arr.push($(this).val())
      }
    });
    user_types = $('#user_type_').val();
    $.ajax({
      type: 'GET',
      data: {user_types: arr},
      url: '/admin/fetch_users',
      success: function (data) {
      }
    });
  });
</script>

app/views/admin/admin/_choose_users.html.erb
<div class="priv_col_wrapper">
  <div class="sel_col mrg_bot_zero">
    <h4>Users</h4>
    <a class="select_txt select_user_all" href="javascript:;">Select All</a>
  </div>
  <div class="custom_checbox_list admin_tic_chkbox">
    <ul>
      <%users.each do |user|%>
        <li>
          <input type="checkbox" class="sel_user" name="user_ids[]" id="user_<%=user.id%>" value="<%=user.id%>" />
          <label for="user_<%=user.id%>"><%= user.name %></label>
        </li>
      <%end%>
    </ul>
  </div>
</div>
<script type="text/javascript">
  $('.select_user_all').click(function(){
    $('.sel_user').click();
  });
</script>

app/views/admin/admin/dashboard.html.erb
<div class="hgt_auto">
  <div class="header_top_row">
    <span class="back_btn"><%=link_to 'Admin Dashboard', :back%></span>
    <span class="menu_icons">
      <div class="submenu_toggle">
        <ul>
          <li><a href="/">Home</a></li>
          <%if current_user%>
            <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
          <%end%>
        </ul>
      </div>
    </span>
  </div>
</div>
<div class="mid_wrapp">
    <div class="super_admin_lft"> 
      <div class="admin_prof_img">
        <%=image_tag 'admin_prof_img.jpg'%>
      </div>
      <div class="edit_prof_text">
        <h4>Tareq <br>Gholam</h4><p>Norway</p>
        <a href="#" class="edt_prof_btn">Edit Profile</a>
      </div>
    </div>
    <div class="notif_left_col super_admin_rht">
      <ul>
        <li>
          <a href="<%=import_new_admin_customers_path%>">
            <%=image_tag 'customer_icon.jpg'%>
            <span class="ser_heading">Customer</span>
          </a>
        </li>
          
        <li class="prev_box">
          <a href="<%=admin_select_privilege_path%>">
            <%=image_tag 'previledge.jpg'%>
            <span class="ser_heading">Priviledge</span>
          </a>
        </li>
          
        <li class="fun_box"> 
          <a href="<%=admin_functionality_path%>">
            <%=image_tag 'setting_icon.jpg'%> 
            <span class="ser_heading">Functionality</span>
          </a>
        </li>
         
      </ul>
   </div>
  </div>

app/views/admin/admin/fetch_customer_types.js.erb
<%if params[:from] && params[:from] == 'todo'%>
  $('#show_customer_type').html("<%=j render 'admin/todos/choose_customer_type', customer_types: @customer_types%>")
<%else%>
  $('#show_customer_type').html("<%=j render 'choose_customer_type', customer_types: @customer_types, multi_select: @multi_select, path: @path%>");
  <%if @customer_types.blank?%>
    $('#show_customer').html("<%=j render 'choose_customer', customers: Daycare.none, multi_select: @multi_select, path: @path%>");
  <%end%>
<%end%>

app/views/admin/admin/fetch_customers.js.erb
<%if params[:from] && params[:from] == 'todo'%>
  $('#show_customer').html("<%=j render 'admin/todos/choose_customer', customers: @customers%>")
<%else%>
  $('#show_customer').html("<%=j render 'choose_customer', customers: @customers,  multi_select: @multi_select, path: @path%>")
<%end%>

app/views/admin/admin/fetch_users.js.erb
<% if @success %>
  $('#show_users').html("<%=j render 'admin/admin/choose_users', users: @users%>");
<% else %>
  $('#show_users').html('');
<% end %>

app/views/admin/admin/functionality.html.erb
<div class="hgt_auto">
  <div class="header_top_row">
    <span class="back_btn"><%=link_to 'Functionality', :back%></span>
    <span class="menu_icons">
      <div class="submenu_toggle">
        <ul>
          <li><a href="/">Home</a></li>
          <%if current_user%>
            <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
          <%end%>
        </ul>
      </div>
    </span>
  </div>
</div>
<div class="mid_wrapp padd34">
  <!-- <div class="priv_col_wrapper">
    <div class="d_input_wrap">
      <ul>
        <li><a href="javascript:;">Country</a>
          <span class="blue_norway"><%#=select_tag(:country,options_for_select(countries), class: 'country_select')%></span>
        </li>
        <li><a href="javascript:;">Language</a>
          <span class="blue_norway"><%#=select_tag(:language,options_for_select(languages), class: 'language_select')%></span>
        </li>
        <li><a href="#">Customer</a>
          <span class="blue_norway">Single</span>
        </li>
      </ul>
    </div>
  </div> -->
  <div class="previlidge_category functi_category">
    <ul>
      <li>
        <a href="#">
          <%=image_tag 'alleragy_icon_1.jpg'%>
          <span class="ser_heading">Allergy</span>
        </a>
      </li>
      <li class="prev_box">
        <%=link_to todos_admin_todos_path do %>
          <%=image_tag 'todo_list_icon_1.jpg'%>
          <span class="ser_heading">Todo List</span>
        <%end%>
      </li>
    </ul>
  </div>
</div>

app/views/admin/admin/login.html.erb
<div class="vertical_mid_center">
  <div class="welcome_col">
    <div class="login_wrapper">
      <h5>Superadmin Login</h5>
      <div class="login_popup">
        <%=image_tag 'login_logo.jpg', width: '236', height: '133', class: 'login_logo', alt: 'Healthcare'%>
        <%=form_tag '/admin/login', method: :post do %>
          <%=email_field_tag :email, nil, class: 'user_icon', placeholder: 'Email', required: true%>
          <%=password_field_tag :password, nil, class: 'password_icon', placeholder: 'Password', required: true%>
          <%=submit_tag 'Login', class: 'login_btn'%>
        <%end%>
      </div>
      <a href="#" class="forget_passwrd">Forgot Password?</a>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('body').addClass('welcome_body');
</script>

app/views/admin/admin/select_privilege.html.erb
<div class="header_top_row green_header">
  <span class="back_btn"><%=link_to 'Privilege', :back %></span>
  <span class="menu_icons">
    <div class="submenu_toggle green_submenu">
      <ul>
        <li><a href="/">Home</a></li>
        <%if current_user%>
          <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
        <%end%>
      </ul>
    </div>
  </span>
</div>

<div class="mid_wrapp padd34">
  <div class="priv_col_wrapper">
    <div class="priv_col_wrapper">
      <div class="d_input_wrap">
        <%=form_tag admin_fetch_customer_types_path, method: :get, remote: true do %>
          <ul>
            <li>
              <a href="javascript:;">Country</a>
              <span class="blue_norway"><%=select_tag(:country, options_for_select(countries), class: 'country_select')%></span>
            </li>
            <li>
              <a href="javascript:;">Language</a>
              <span class="blue_norway"><%=select_tag(:language,options_for_select(languages), class: 'language_select', id: 'select_country')%></span>
            </li>
          </ul>
        <%end%>
      </div>
    </div>

    <div id="show_customer_type"></div>
    <div id="show_customer"></div>
    <div id="show_functionality"></div>

  </div>
</div>

app/views/admin/admin/set_privilege.html.erb
<div class="header_top_row green_header">
  <span class="back_btn"><%=link_to 'Privilege', :back %></span>
  <span class="menu_icons">
    <div class="submenu_toggle green_submenu">
      <ul>
        <li><a href="/">Home</a></li>
        <%if current_user%>
          <li><%=link_to 'Logout', destroy_user_session_path, method: :delete%></li>
        <%end%>
      </ul>
    </div>
  </span>
</div>
<div class="mid_wrapp padd34">
  <div class="previlidge_category">
    <%=form_tag admin_set_privilege_path, method: :post do%>
      <%=hidden_field_tag :daycare_id, params[:daycare_id] %>
      <%=hidden_field_tag 'user_type[]', params[:user_type] %>
      <%=hidden_field_tag :functionality, params[:functionality]%>

      <div class="custom_checbox_list check_privilege">
        <ul>
          <li>
            <a href="javascript:;" class="check_label">
              <%=image_tag 'create_icon_1.jpg'%>
              <input type="checkbox" class="user_type_common" name="permission_type[]" id="create" value="CreatePermission" />
              <label class="ser_heading mar_0" for="create">Create</label>
            </a>
          </li>
          <li class="prev_box">
            <a href="javascript:;">
              <%=image_tag 'edit_icon_1.jpg'%>
              <input type="checkbox" class="user_type_common" name="permission_type[]" id="edit" value="EditPermission" />
              <label class="ser_heading mar_0" for="edit">Edit</label>
            </a>
          </li>
          <li class="fun_box"> 
            <a href="javascript:;">
              <%=image_tag 'view_icon.jpg'%>
              <input type="checkbox" class="user_type_common" name="permission_type[]" id="view" value="ViewPermission" />
              <label class="ser_heading mar_0" for="view">View</label>
            </a>
          </li>
          <li class="fun_box"> 
            <a href="javascript:;">
              <%=image_tag 'report_icon_1.jpg'%>
              <input type="checkbox" class="user_type_common" name="permission_type[]" id="report" value="ReportPermission" />
              <label class="ser_heading mar_0" for="report">Report</label>
            </a>
          </li>
        </ul>
      </div>
      <div class="green_btn_wrapper">
        <%=submit_tag 'Apply', class: 'submit_btn green_btn'%>
      </div>
    <%end%>
  </div>
</div>